const ACTIONS = {
  'CLIENTS_FETCH': 'CLIENTS_FETCH',
  'USER_LOGIN': 'USER_LOGIN',
  'USER_LOGOUT': 'USER_LOGOUT',
  'USER_FETCH': 'USER_FETCH',
  'INVOICE_ADD': 'INVOICE_ADD',
  'INVOICE_UPDATE': 'INVOICE_UPDATE',
  'INVOICE_REMOVE': 'INVOICE_REMOVE'
};

export default ACTIONS;
