const ACTIONS = {
  'CLIENTS_FETCH': 'CLIENTS_FETCH',
  'USER_LOGIN': 'USER_LOGIN',
  'USER_LOGOUT': 'USER_LOGOUT',
  'USER_FETCH': 'USER_FETCH',
  'INVOICES_FETCH': 'INVOICES_FETCH',
  'INVOICES_ADD': 'INVOICES_ADD',
  'INVOICES_UPDATE': 'INVOICES_UPDATE',
  'INVOICES_REMOVE': 'INVOICES_REMOVE',
  'INVOICES_CHANGE_MONTH': 'INVOICES_CHANGE_MONTH',
  'INVOICES_ADD_EMPTY': 'INVOICES_ADD_EMPTY'
};

export default ACTIONS;
